version: '3'

services:
  kpp-veb:
    build: ./servisi/veb-kpp/
    volumes:
      - ./servisi/veb-kpp/react-kpp:/app
    ports:
      - 3000:3000
    depends_on:
      - kpp-baza-zaposleni
      - kpp-baza-procesi
  kpp-mikroservis-zaposleni:
    build: ./servisi/mikroservis-zaposleni/
    ports:
      - 3001:80
    depends_on:
      - kpp-baza-zaposleni
  kpp-mikroservis-procesi:
    build: ./servisi/mikroservis-procesi/
    ports:
      - 3002:80
    depends_on:
      - kpp-baza-procesi
  kpp-baza-zaposleni:
    build: ./servisi/baza-zaposleni/
    ports:
      - 3005:1433
  kpp-baza-procesi:
    build: ./servisi/baza-procesi/
    ports:
      - 3006:1433